### ISSUE TITLE
(global-column-enforce-mode t) not work

### ISSUE THREAD

**Issue by quanyufang** [jordonbiondo/column-enforce-mode#6]
I put (global-column-enforce-mode t)  at last line of my init.el, there still error message :
`Symbol's function definition is void: global-column-enforce-mode `

But I can use:
`(add-hook 'prog-mode-hook 'column-enforce-mode)`
It works.

**Comment by jordonbiondo** [comment]
Thanks, looks like I was missing an autoload cookie on the global mode: should be fixed with 019873a94742ec85c9b6a2587ae29545e6a7662e.
