### ISSUE TITLE
Changing column-enforce-column not working

### ISSUE THREAD

**Issue by aaronbee** [jordonbiondo/column-enforce-mode#7]
In HEAD f7bea84f35ed1b9ca3f953d512047e20b90d5cbd changing the column length is not working. It always enforces 80 characters. This is working fine with commit 492d757400a3c6dbdeec5206a1f5f7799d55328b from May 22, 2015.

**Comment by dkogan** [comment]
Look in (column-enforce-get-column). It computes a getter function, but doesn't use it. (funcall getter) in that function, and it should work.

**Comment by jordonbiondo** [comment]
Thanks @aaronbee  and @dkogan 858a49daca67188cbcc151a7b531556552d48d00 should fix this issue.
