### ISSUE TITLE
feature request: column-enforce-inhibit-major-modes

### ISSUE THREAD

**Issue by chadhs** [jordonbiondo/column-enforce-mode#8]
feature request: column-enforce-inhibit-major-modes

could we define a var `column-enforce-inhibit-major-modes` (or similar) to allow folks to enable column-enforce-mode globally, but exclude certain modes?

i'm an elisp newbie but would be willing to help if you're in favor of the idea.  thanks!

**Comment by jordonbiondo** [comment]
I opted initially for a more open-ended approach that can be used to implement the behavior you want. See this PR: #9 for an example of what you requested. If that works for you, I'll push that change out.
